### ISSUE TITLE
About OCR

### ISSUE THREAD

**Issue by cdvalera** [betri28/FaceDetectCamera#2]
Hi Nguyen  
 
Your face detection tutorial is excellent and I realize that you did it before google launched "google.vision.api", your app is as fast as google.
My question is: how can I add text recognition in your app at the same time that it detects faces ???. I have tried to use the google api with the following code in the main detection thread as folows:

 public void run() {
//            Log.i("FaceDetectThread", "running");

            float aspect = (float) previewHeight / (float) previewWidth;
            int w = prevSettingWidth;
            int h = (int) (prevSettingWidth * aspect);

            ByteBuffer bbuffer = ByteBuffer.wrap(data);
            bbuffer.get(grayBuff, 0, bufflen);

            gray8toRGB32(grayBuff, previewWidth, previewHeight, rgbs);
            Bitmap bitmap = Bitmap.createBitmap(rgbs, previewWidth, previewHeight, Bitmap.Config.RGB_565);
            Bitmap bmp = Bitmap.createScaledBitmap(bitmap, w, h, false);
            Bitmap bmp2 = bmp.copy(Bitmap.Config.ALPHA_8, true);

            float xScale = (float) previewWidth / (float) prevSettingWidth;
            float yScale = (float) previewHeight / (float) h;

            Camera.CameraInfo info = new Camera.CameraInfo();
            Camera.getCameraInfo(cameraId, info);
            int rotate = mDisplayOrientation;
            if (info.facing == Camera.CameraInfo.CAMERA_FACING_FRONT && mDisplayRotation % 180 == 0) {
                if (rotate + 180 > 360) {
                    rotate = rotate - 180;
                } else
                    rotate = rotate + 180;
            }

            switch (rotate) {
                case 90:
                    bmp = ImageUtils.rotate(bmp, 90);
                    xScale = (float) previewHeight / bmp.getWidth();
                    yScale = (float) previewWidth / bmp.getHeight();
                    break;
                case 180:
                    bmp = ImageUtils.rotate(bmp, 180);
                    break;
                case 270:
                    bmp = ImageUtils.rotate(bmp, 270);
                    xScale = (float) previewHeight / (float) h;
                    yScale = (float) previewWidth / (float) prevSettingWidth;
                    break;
            }

            try {
                if (TextDetector.isOperational() && bmp2 != null) {
                    Frame frame = new Frame.Builder().setBitmap(bmp2).build();
                    SparseArray<TextBlock> textBlocks = TextDetector.detect(frame);
                    String blocks = "";
                    for (int index = 0; index < textBlocks.size(); index++) {
                        //extract scanned text blocks here
                        TextBlock tBlock = textBlocks.valueAt(index);
                        blocks = blocks + tBlock.getValue() + "\n" + "\n";
                        Log.d("FaceDetectThread", blocks.toString());
                    }

                } else {

                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            fdet = new android.media.FaceDetector(bmp.getWidth(), bmp.getHeight(), MAX_FACE);
            android.media.FaceDetector.Face[] fullResults = new android.media.FaceDetector.Face[MAX_FACE];
            fdet.findFaces(bmp, fullResults);

            for (int i = 0; i < MAX_FACE; i++) {
                if (fullResults[i] == null) {
                    faces[i].clear();
                } else {
                    PointF mid = new PointF();
                    ...
...
...
...
...
...
...

But it gives me an error in the log like : 

A/native: jni_helper.cc:110 Bitmap is of the wrong format: 8
A/native: terminating.
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 19786 (Thread-11364)

Should I use google api in app or I have to do it differently
differently?
Could you help me on this??
Thanks in advance...
Christian

**Comment by betri28** [comment]
To add text, you need view class facedetectcamera/activity/ui/FaceOverlayView.java . This is a View overlay the SurfaceView in main layout. By Override onDraw you can add text in this view:

canvas.drawRect //add Rect
canvas.drawText //add Text

In my project, I already add some text to the face: ID, Confidence , EyesDistance.

**Comment by cdvalera** [comment]
Thanks for your quick response. Maybe I was not explicit enough to explain
what I'm trying to do. I try to add OCR in your project, that is to say, to
be able to detect the face of a person and at the same time to detect text
for example of an identification card. My question was if I can use the API
(mobile.vision.api) from google in your project, since I have tried to do
it with this code within the FaceDetectThread but not such luck.

According to the ocr manual of the api all I need is: 1) Create or obtain
the Bitmap, which is already created in your code (Bitmap bmp) 2)
Initialize the detector 3) Create a frame using the default bitmap and call
on the Text detector

In point 3 is the problem...

if (TextDetector.isOperational() && bmp != null) {

    Frame frame = new Frame.Builder().setBitmap(bmp).build();
    SparseArray<TextBlock> textBlocks = TextDetector.detect(frame);
    String blocks = "";
    for (int index = 0; index < textBlocks.size(); index++) {
        //extract scanned text blocks here
        TextBlock tBlock = textBlocks.valueAt(index);
        blocks = blocks + tBlock.getValue() + "\n" + "\n";
        Log.d("FaceDetectThread", blocks.toString());
    }

} else {}


And When debugging the error comes at line:

"SparseArray<TextBlock> textBlocks = TextDetector.detect(frame);"

And in the log:


E/art:
Thread[16,tid=26986,Suspended,Thread*=0xb81be260,peer=0x12c480b0,"Thread-11841"]
suspend count too deep for method invocation: 2
A/native: jni_helper.cc:110 *Bitmap is of the wrong format: 4*
A/native: terminating.
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 26986 (Thread-11841)

Than you in advance...

Christian from Ecuador....



El mié., 5 abr. 2017 a las 10:49, Nguyen Minh Tri (<notifications@github.com>)
escribió:

To add text, you need view class
facedetectcamera/activity/ui/FaceOverlayView.java . This is a View overlay
the SurfaceView in main layout. By Override onDraw you can add text in this
view:

canvas.drawRect //add Rect
canvas.drawText //add Text

In my project, I already add some text to the face: ID, Confidence ,
EyesDistance.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/betri28/FaceDetectCamera/issues/2#issuecomment-291905390>,
or mute the thread

**Comment by betri28** [comment]
I read doc of [TextRecognizer](https://developers.google.com/android/reference/com/google/android/gms/vision/text/TextRecognizer) 

```
public SparseArray<TextBlock> detect (Frame frame)

Detects and recognizes text in a image. Only supports bitmap and NV21 for now.

Returns
mapping of int to TextBlock, where the int domain represents an opaque ID for the text block.
```

As you see "Only supports bitmap and NV21 for now". I think the error come from format of bitmap you put into detector. 

**Solution in FaceDetectThread :**

```
ByteBuffer bbuffer = ByteBuffer.wrap(data);

Frame outputFrame = new Frame.Builder()
                            .setImageData(bbuffer , previewWidth,
                                    previewHeight, ImageFormat.NV21)
                            .setRotation(mRotation)
                            .build();

SparseArray<TextBlock> textBlocks = TextDetector.detect(outputFrame);
```

**Comment by cdvalera** [comment]
Hi Nguyen..
I don't know how to thank you enough... Thank you for your time, patience
an generosity... It is working just fine....

Christian from Ecuador...
